### ISSUE TITLE
minecraft crash in server because of mech

### ISSUE THREAD

**Issue by Ereebay** [Demitto/Flan-s-Mod-Plus#14]
I use the Flan plus 1.0.4 and the titan content pack which improved by prototypetheta.But it will crash the game sometimes in server.And this is the crash report:
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 4/13/17 8:29 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.flansmod.client.model.ModelMecha.render(ModelMecha.java:105)
	at com.flansmod.client.model.ModelMecha.render(ModelMecha.java:48)
	at com.flansmod.client.model.RenderMecha.render(RenderMecha.java:76)
	at com.flansmod.client.model.RenderMecha.func_76986_a(RenderMecha.java:351)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:313)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:291)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:264)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:737)
	at shadersmod.client.ShadersRender.renderShadowMap(ShadersRender.java:375)
	at shadersmod.client.Shaders.beginRender(Shaders.java:4029)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1525)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1391)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

it seems like the render problem.

**Comment by voidswrath** [comment]
.
